### ISSUE TITLE
Introducción a la programación

### ISSUE THREAD

**Issue by nelsonvilte** [FedeCorres/RepositorioGrupal#12]
Escribir el código en Python que permita realizar lo siguiente:
2)   Crear una lista en Python denominada “Dueno2”  y recorrerla con un bucle  mostrando sus elementos por pantalla con excepción del DNI y el apellido. Los elementos de la lista son:

           23546987,  “Maria”,  “Perez”, 4789689,  “Pueyrredon  811”

 que representan los datos del dueño de un perro (DNI, nombre, apellido, teléfono y dirección)

**Comment by yacocapdevila** [comment]
3)  Crear un lista en Python denominado “Perro” que contenga los siguientes valores:

  13,  Puppy,  12/12/2012 , Macho, 123

Que se corresponde con los datos de un perro de nuestra base de datos (Id_Perro, nombre, fecha de nacimiento, sexo y dni del dueño). Modificar la fecha de nacimiento por 13/12/2012 y reemplazar “dni del dueño” por 28957346 .

**Comment by veromeme1900** [comment]
10) Crear una lista denominada “Clientes” con los nombres de los diferentes  dueños de perros.

          Juan,  Mario,  Ariel,  Josefina,  Marianella.

Ordenarla alfabéticamente y mostrarla por pantalla
