### ISSUE TITLE
Base de Datos

### ISSUE THREAD

**Issue by nelsonvilte** [FedeCorres/RepositorioGrupal#13]
Subir un script SQL que constará, de la creación de la base de datos con sus tablas y los datos necesarios en las mismas, para poder realizar una consulta a elección por estudiante (de los propuestos desde el Nro 3 al 12) y subirlo posteriormente a su propia rama en el GitHub.

**Consulta elegida:** 

5. Realice una consulta multitabla que arroje el nombre de todos los perros cuyos dueños se llaman Pedro

**Comment by yacocapdevila** [comment]
Subir un script SQL que constará, de la creación de la base de datos con sus tablas y los datos necesarios en las mismas, para poder realizar una consulta a elección por estudiante (de los propuestos desde el Nro 3 al 12) y subirlo posteriormente a su propia rama en el GitHub.

Elección:
 4.Actualice la fecha de nacimiento de algún animal (perro) que usted considere.
