### ISSUE TITLE
Concepto Scrum

### ISSUE THREAD

**Issue by FedeCorres** [FedeCorres/RepositorioGrupal#2]
Extraer del material de Scrum los siguientes conceptos: Ceremonias, Artefactos y Roles.

**Comment by veromeme1900** [comment]
Concepto de ceremonia y cuales son                                                 
Las ceremonias de la metodología Scrum son elementos importantes del proceso de desarrollo de software de Agile. No son reuniones sólo por el hecho de reunirse. Más bien, estas ceremonias de Scrum proporcionan el marco para que los equipos realicen el trabajo de manera estructurada, ayuden a establecer expectativas, capaciten al equipo para colaborar de manera efectiva y, en última instancia, alcancen los resultados. Sin embargo, si no se administran de manera adecuada, pueden abrumar el calendario y bajar un poco el valor que deben proporcionar.
● Sprint Planning Meeting (reunión de planificación del sprint). Se produce al iniciar cada Sprint y tiene por objetivo decidir que se va a realizar en el Sprint.
● Daily Scrum Meeting (reunión periódica). Se produce diariamente, y tiene un máximo de 20 min. de duración. Tiene por objeto tratar qué es lo que se hizo, qué se va a hacer y qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.
● Sprint Review Meeting (reunión de revisión del Sprint). Se produce al finalizar el Sprint y tiene por objeto mostrar qué es lo que se ha completado y qué no. Debe estar presente el Product Owner.
● Sprint Retrospective Meeting (reunión de retrospectiva del Sprint). Se produce también al finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.

Artefactos de Scrum

Pila de producto (backlog product)
Pila de Sprint
Incremento

Roles Scrum
●Product Owner (PO)
●Scrum master
●Development team
●Customers
